public enum TOKEN_TYPE {
    ID,
    NUM,
    EQ,
    PLUS,
    TIMES,
    SEMI,
    MINUS,
    OPEN_PARENTHESIS, // (
    CLOSE_PARENTHESIS, // )
    OPEN_BRACKETS, // {
    CLOSE_BRACKETS, // }
    OPEN_ANGLEBRACKETS, // [
    CLOSE_ANGLEBRACKETS, // ]
    LESS_THAN,
    BIGGER_THAN,
    PRINT,
    WHILE,
    TYPE,
    BOOLEAN,
    RESERVED_WORD,
    RETURN_TYPE_ATTRIBUTTION,
    TYPE_ATTRIBUTTION,
}
