public enum TOKEN_TYPE {
    ID,
    NUM,
    FLOAT,
    EQ,
    PLUS,
    TIMES,
    SEMI,
    MINUS,
    DIVISION,
    PERCENT_SIGN,
    COMMA,
    EQUAL,
    DOT,
    DIFFERENCE,
    CONJUNCTION,
    DISJUNCTION,
    NULL,
    CHAR,
    BACKSLASH,
    LOGICAL_NEGATION,
    OPEN_PARENTHESIS, // (
    CLOSE_PARENTHESIS, // )
    QUOTATION, // '
    OPEN_BRACKETS, // {
    CLOSE_BRACKETS, // }
    OPEN_ANGLEBRACKETS, // [
    CLOSE_ANGLEBRACKETS, // ]
    LESS_THAN,
    BIGGER_THAN,
    PRINT,
    WHILE,
    TYPE,
    BOOLEAN,
    RESERVED_WORD,
    RETURN_TYPE_ATTRIBUTTION,
    TYPE_ATTRIBUTTION,
}
